### ISSUE TITLE
Install fails on OS 10.11

### ISSUE THREAD

**Issue by strider72** [lbryio/lbry-setup#17]
Here's what I get in Terminal.  You see the error towards the end.  Seems to install (sort of) but none of the commands are findable in Terminal.  Can't run lbrynet-console or lbrynet-daemon.

Note I'm logged in as non-admin account in OS X, but I used su admin before running install script.

```
Installing LBRY and dependancies
Xcode command line tools already installed...
Updating brew...
Installing mpfr...
Installing pip...
Installing gmpy...
Installing service_identity...
Installing rumps...
Installing six 1.9.0 for python...
Downloading and installing lbryum
Downloading and installing lbrynet
Downloading web ui to ~/Downloads
Cloning lbry app repository and moving to /Applications...
usage: dirname path
  File "<string>", line 1
    import sys; print str.join(':', (sys.path))[1:]
                        ^
SyntaxError: invalid syntax
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Starting LBRY, check your status bar!
LBRY.app has been installed to your Applications folder
```

**Comment by jackrobison** [comment]
Although it's probably unrelated, I found that six was reverting to an older version and might have caused a problem. Try running the installer again to get the update.

After, here's some things to try out:

Does `python -c 'import lbrynet, lbryum'` return an error?

The command it's not liking is where it makes a copy of PATH and PYTHONPATH so the process launched by the app knows where to look. Even without binaries to run you should be able to see if lbrynet is properly installed by running the following to (hopefully) start the daemon:

`python -c "from lbrynet.lbrynet_daemon.LBRYDaemon import main; main()"`

If that works you should be able to connect to it with the status bar app (LBRY.app)

If you want to shut it down manually:

`python -c "from lbrynet.lbrynet_daemon.LBRYDaemon import stop; stop()"`

**Comment by strider72** [comment]
Hrm.  Similar to before:

```
Removing lbrynet installation from /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
Installing LBRY and dependancies
Xcode command line tools already installed...
Updating brew...
Installing mpfr...
pip already installed
Installing gmpy...
Installing service_identity...
Installing rumps...
Downloading and installing lbryum
Downloading and installing lbrynet
Downloading web ui to ~/Downloads
Cloning lbry app repository and moving to /Applications...
usage: dirname path
  File "<string>", line 1
    import sys; print str.join(':', (sys.path))[1:]
                        ^
SyntaxError: invalid syntax
* * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Starting LBRY, check your status bar!
LBRY.app has been installed to your Applications folder
```

The python commands gives me:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lbryum-2.6-py3.5.egg/lbryum/__init__.py", line 1, in <module>
    from version import ELECTRUM_VERSION
ImportError: No module named 'version'
```

**Comment by jackrobison** [comment]
Looks like you're using python 3.5, lbry needs 2.7

**Comment by strider72** [comment]
Thought of that. Thought I could run "python27" but it's not working.  Hm...

**Comment by jackrobison** [comment]
I never use python 3, it hadn't occurred to me. I'll have to make the script check which version the default python is, and make sure it uses 2.7 regardless. If you can easily change your default 'python' to 2.7 that should do it in the mean time.

The path to python 2.7 on my machine is `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`

**Comment by strider72** [comment]
Sorry if I should be starting a separate Issue for this. Still fits under the rather generic topic I gave it....

Changing default python to v2 fixed it, to an extent.

Different issues though... The menubar client is looking for files in the "Downloads" folder. Is that normal? Because I used su admin, it's looking in the admin user's folder rather than my own. Perhaps DL folder is not the best place to put important program files?

Also: none of the cli commands are findable.   Perhaps a directory not added to the PATH properly?  Can't run lbrynet-console ; can't run lbrynet-daemon

Running daemon using the long command you gave above does work, but errors:

```
bash-3.2$ python -c "from lbrynet.lbrynet_daemon.LBRYDaemon import main; main()"
Loading databases...
Using lbryum wallet
Autofetcher using default max key price of 0.0
To change this create the file:
/Users/Admin/Library/Application Support/lbrycrd/autofetcher.conf
Example contents of conf file:
maxkey=1.0
Started LBRYnet daemon
The daemon can be shut down by running 'stop-lbrynet-daemon' in a terminal
Startup message: Connected to LBRYnet
2016-03-03 16:07:17.758 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-03-03 16:07:17.759 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-03-03 16:07:17.759 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-03-03 16:07:17.760 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-03-03 16:07:17.761 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-03-03 16:07:17.763 osascript[42886:175875] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
```

I appreciate the help.  Let me know what info you need.
