### ISSUE TITLE
Install Fails OSX 10.11.3

### ISSUE THREAD

**Issue by jamesontriplett** [lbryio/lbry-setup#18]
This is the second try at installing:  
I installed from the pkg file explained here: 
https://github.com/lbryio/lbry-setup/blob/master/README_OSX.md

Installing LBRY and dependancies
Xcode command line tools already installed...
Updating brew...
Installing mpfr...
pip already installed
Installing gmpy...
service_identity already installed...
rumps already installed...
Downloading and installing lbryum
Downloading and installing lbrynet
Downloading web ui to ~/Downloads
Cloning lbry app repository and moving to /Applications...
Starting LBRY, check your status bar
You can start the app from your Applications folder
jamesontriplett@JTriplett:~$ lbrynet-console
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-console", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 2837, in <module>
    
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 449, in _build_master
    self.add(dist, entry, False)
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 742, in require
    
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 639, in resolve
    req = [dist.as_requirement()]
pkg_resources.DistributionNotFound: leveldb

**Comment by jamesontriplett** [comment]
This was resolved by installing pip, and then installing 
sudo pip install leveldb

Then the Error moved (progress!) 
'''
pkg_resources.DistributionNotFound: unqlite==0.2.0
'''

**Comment by jamesontriplett** [comment]
`sudo pip install python`
... success
`sudo pip install unqlite`
... success

Running Console again:
sudo lbrynet-console
Traceback (most recent call last):
  File "/usr/local/bin/lbrynet-console", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 2837, in <module>
    
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 451, in _build_master
    def __contains__(self,dist):
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 464, in _build_from_requirements
    """
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources.py", line 639, in resolve
    req = [dist.as_requirement()]
pkg_resources.DistributionNotFound: unqlite==0.2.0

**Comment by jamesontriplett** [comment]
`sudo pip install unqlite==0.2.0`
... success 

Yikes: 
`pkg_resources.DistributionNotFound: txJSON-RPC`

**Comment by jamesontriplett** [comment]
Packages needing to be installed:
txJSON-RPC
python-bitcoinrpc==0.1
... successes

seccure
... failed

```
ions/2.7/include/python2.7 -c src/gmpy.c -o build/temp.macosx-10.11-intel-2.7/src/gmpy.o
    In file included from src/gmpy.c:251:
    ./src/gmpy.h:30:10: fatal error: 'gmp.h' file not found
    #include "gmp.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

```

**Comment by jamesontriplett** [comment]
Ok installing GMP looks like a big task I'm not up for right now. Anyway to make this better?

I'm a java guy, this python stuff is just a snake in the grass...

**Comment by jamesontriplett** [comment]
Ok, a few more minutes at this: 
Re-installed Brew (hadn't used since ElCap upgrade) 
brew install gmp
pip install gmpy
pip install seccure
miniupnpc-1.9

Guys guys, there has got to be an easier way...

**Comment by jamesontriplett** [comment]
Finally did the whole:
jamesontriplett@JTriplett:~$ brew install autoconf automake libtool boost openssl pkg-config protobuf qt5 git gmp


Did a pip install twisted

Finally: console works:

> get wonderfullife

Finally worked... But that was a lot of work.  Anyway to trim up that installer?

**Comment by kauffj** [comment]
:+1: to @jamesontriplett for working through what looks like nearly an hour long install process. We'll look at this and figure out a way to clean it up! I know @jackrobison is already hard at work on a cleaner, native, non-sudo based installer.

**Comment by jackrobison** [comment]
>Re-installed Brew (hadn't used since ElCap upgrade)

This sounds like it might be the root of the issue, was your pip installation also pre-upgrade?

The installer appears to have thought it installed gmpy, although if it was to a pre el capitan directory it might not have worked. That's why after re-installing brew it would work properly.

As for the python packages, those should be installed when the script runs the setup.py files, but again if the version of pip was pre-upgrade it might have tried to do so in a directory it no longer has permission to install to.

Sounds like I've gotta have it not only detect if the programs are installed (which it thought they were), but also where they're installed.
